version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
